name: seldat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0'

dependencies:
  flutter:
    sdk: flutter
  win32: ^5.5.1
  win32_registry: ^1.1.3
  google_fonts: ^6.2.1
  window_manager: ^0.3.9
  fl_chart: ^0.68.0
  sqflite:
  sqflite_common_ffi: any
  xml: ^6.5.0
  paged_datatable: ^2.0.1
  tflite_flutter: ^0.10.4
  koala: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# dependency_overrides:
#   intl: ^0.19.0

flutter:
  uses-material-design: true
